# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Changes last_call.txt to current time
  rundeadman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Pull
      run: git pull
    - name: Run Deadman Switch
      run: python ./index.py "${{secrets.URL}}" "${{secrets.MESSAGE}}"
    - name: Push
      run: |
        git config --global user.name 'Github Actions Bot'
        git config --global user.email '<>'
        git status
        git add last_call.txt
        git status
        git commit -m "Update last_call.txt"
        git status
        git push
        git status
