# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Changes last_call.txt to current time
  changetxt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - name: Change last_call.txt using python
      run: python ./.github/workflows/change.py
    - name: Commit report
      run: |
        git status
        git config --global user.name 'Github Actions Bot'
        git config --global user.email '<>'
        git add last_call.txt
        git commit -m "Update last_call.txt"
        git pull --rebase
        git status
        git add last_call.txt
        git push
