# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Changes last_call.txt to current time
  changetxt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Change last_call.txt using python
      run: python ./.github/workflows/change.py
    - name: Commit report
      continue-on-error: true
      run: |
        git config --global user.name 'Github Actions Bot'
        git config --global user.email '<>'
        git add last_call.txt
        git commit -m "Update last_call.txt"
    - name: Force Push 
      run: |
        git push --force
        git status
